### ISSUE TITLE
[Stremio] Failed to fetch error

### ISSUE THREAD

**Issue by Wolfynator** [n0bodysec/docker-images#6]
Installed docker engine, started container with `docker run --rm -p 8080:8080 -p 8081:8081 -p 11470:11470 -e APPLY_PATCHES=1 -e FIX_UNSUPPORTED_MEDIA=1 -e NO_CORS=1 -v ${PWD}:/root/.stremio-server n0bodysec/stremio`, and accessed the webui on 8081. Streaming server IP in settings set to 127.0.0.1 but failed to fetch whenever I try to stream anything. Firewall allows ports 11470, 8080-8081.

**Comment by n0bodysec** [comment]
Hello, please check if the stremio server is accessible on 127.0.0.1:11470.

You need to configure the webui to point to "127.0.0.1:11470" if you are passing the server port to the host using `-p`.

Also, if you don't want or you can't specify a port for any reason, you can set up a reverse proxy both for webui and the streaming server (this is my setup).

If none of this works, please try to use the dev image to fetch the latest version of the server.

`docker compose -f docker-compose.dev.yml up -d`.

Regards.

**Comment by Wolfynator** [comment]
Hi, thanks for taking the time to reply.

It seems to be working when I configure the streaming server IP to my machine's public IP with the port 11470. I used the dev image here as well but configuring as 127.0.0.1:11470 still has the error. So it works now, but in a weird way?

For context, I am running your container on a debian server and accessing the web gui via it's public IP at 8081. Then configuring the streaming server in settings to point to the same public IP at 11470. Like I mentioned, doing it this way works, but pointing to 127.0.0.1:11470 should work as well right?

Maybe I am misunderstanding how docker works, but now the question is if the web gui and the streaming server are on the same machine, why can't the web gui access the streaming server using 127.0.0.1:11470?

I'm guessing changing the `-p` parameters can solve this but I'm not sure and hope you can enlighten me.

**Comment by n0bodysec** [comment]
Well, I barely remember how stremio works since I don't use it on a daily basis.

On docker cli, `-p` exposes the defined port to the host machine since the default network interface on docker is a bridge one.

Also, you can use a host network, so you don't need to manually expose ports.

About stremio, I remember the webui makes the connection to the streaming server on the client side. It means that your streaming server needs to be exposed to your client. So, if you are able to access 127.0.0.1:11470 directly using the web browser, then you should be able to use it on the webui.

**Comment by Wolfynator** [comment]
That makes sense now, I kept thinking that the webui was the client and not the user on the browser loading the webpage. Thanks for clearing that up.

**Comment by n0bodysec** [comment]
You are welcome!
